# Generated by Django 5.1.2 on 2024-11-08 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(max_length=100, verbose_name='岗位')),
                ('employment_status', models.CharField(choices=[('在职', '在职'), ('离职', '离职')], default='在职', max_length=20, verbose_name='在岗状态')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.company', verbose_name='所属公司')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.project', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('入职', '入职'), ('调岗', '调岗'), ('离职', '离职')], max_length=20, verbose_name='变动类型')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('status', models.CharField(choices=[('待确认', '待确认'), ('已确认', '已确认'), ('已拒绝', '已拒绝')], default='待确认', max_length=20, verbose_name='状态')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_changes', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.employee', verbose_name='员工')),
                ('new_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_company', to='mainapp.company', verbose_name='新公司')),
                ('new_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_project', to='mainapp.project', verbose_name='新项目')),
                ('old_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_company', to='mainapp.company', verbose_name='原公司')),
                ('old_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_project', to='mainapp.project', verbose_name='原项目')),
            ],
        ),
    ]
