# Generated by Django 5.1.2 on 2024-11-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(blank=True, null=True, verbose_name='入职日期'),
        ),
        migrations.AddField(
            model_name='employee',
            name='latest_position_date',
            field=models.DateField(blank=True, null=True, verbose_name='最新岗位日期'),
        ),
    ]
