# Generated by Django 5.1.2 on 2024-11-27 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initialize_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(max_length=100, verbose_name='岗位')),
                ('employment_status', models.CharField(choices=[('在岗', '在岗'), ('待岗', '待岗'), ('离职', '离职')], default='待岗', max_length=20, verbose_name='在岗状态')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('latest_position_date', models.DateField(blank=True, null=True, verbose_name='最新岗位日期')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='所属公司')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project', verbose_name='所属项目')),
            ],
        ),
    ]
